#!/usr/bin/env bash

declare x=$(cat "/sys/class/backlight/acpi_video0/brightness")

for i in "$@"; do
  case $i in
    --increase)
      x=$((x+10))
      shift
      ;;
    --decrease)
      x=$((x-10))
      shift
      ;;
    *)
      ;;
  esac
done

if [[ ${x} -lt 0 ]]; then
    x=0
fi

if [[ ${x} -gt 100 ]]; then
    x=100
fi

echo $x > /sys/class/backlight/acpi_video0/brightness
