#!/usr/bin/env bash

QUERY="$(rofi -dmenu -p 'Search Query' -lines 0 -no-fixed-num-lines | jq -Rr @uri)"

if [ "$QUERY" == "" ]; then
    exit 0
fi

xdg-open "https://www.google.com/search?q=${QUERY}"

i3-msg [class="(?i)firefox"] focus
