#!/usr/bin/env bash

# Menu defined as an associative array
typeset -A menu

# Menu with keys/commands
menu=(
  [ Shutdown]="systemctl poweroff"
  [ Reboot]="systemctl reboot"
  [ Suspend]="systemctl suspend"
  [ Cancel]=""
)

menu_nrows=${#menu[@]}

selection="$(printf '%s\n' "${!menu[@]}" | rofi -dmenu -i -lines "${menu_nrows}" -p '')"

if [[ $? -eq 0 && ! -z ${selection} ]]; then
  i3-msg -q "exec ${menu[${selection}]}"
fi
