#!/usr/bin/env python3

import vm_detect
import subprocess
import colors

vm_detect.exit_if_vm()

fontawesome = {
    'battery-empty':          '\uf244', # 
    'battery-full':           '\uf240', # 
    'battery-half':           '\uf242', # 
    'battery-quarter':        '\uf243', # 
    'battery-three-quarters': '\uf241', # 
    'bolt':                   '\uf0e7', # 
    'plug':                   '\uf1e6', # 
}

battery = subprocess.check_output(['acpi', '-b'], universal_newlines=True, stderr=subprocess.DEVNULL)

if not battery:
    print(colors.error('BATTERY NOT FOUND'))

    exit(0)

battery = battery.rstrip('\n')

# Remove name
battery = battery.split(': ')[1]

battery = battery.split(', ')

state = battery[0]

if state == 'Unknown':
    print(colors.error('BATTERY STATE UNKNOWN'))

    exit(0)

percent = int(battery[1].rstrip('%'))

if state == 'Full':
    icon = 'plug'
elif state == 'Charging':
    icon = 'bolt'
elif percent > 80:
    icon = 'battery-full'
elif percent > 60:
    icon = 'battery-three-quarters'
elif percent > 40:
    icon = 'half'
elif percent > 20:
    icon = 'battery-quarter'
else:
    icon = 'battery-empty'

output = '{} {}%'.format(fontawesome[icon], percent)

if percent < 10:
    output = colors.error(output)
elif percent < 20:
    output = colors.warning(output)

print(output)
