#!/usr/bin/env python3

from subprocess import check_output
from subprocess import run

def error(message):
    return "%{F#BF616A}" + message + "%{F-}"

def warning(message):
    return "%{F#EBCB8B}" + message + "%{F-}"

virt_status = run(["systemd-detect-virt"], universal_newlines=True, check=False, capture_output=True).stdout

virt_status = virt_status.rstrip("\n")

if virt_status != "none":
    exit(0)

battery = check_output(["acpi", "-b"], universal_newlines=True)

if not battery:
    print(error("BATTERY NOT FOUND"))
    exit(0)

battery = battery.rstrip("\n")

# Remove name
battery = battery.split(": ")[1]

battery = battery.split(", ")

state = battery[0]

if state == "Unknown":
    print(error("BATTERY STATE UNKNOWN"))
    exit(0)

percent = int(battery[1].rstrip("%"))

if state == "Full":
    icon = "\uf1e6" # Plug symbol
elif state == "Charging":
    icon = "\uf0e7" # Lightning symbol
elif percent > 80:
    icon = "\uf240" # Full battery symbol
elif percent > 60:
    icon = "\uf241" # 3/4 full battery symbol
elif percent > 40:
    icon = "\uf242" # 1/2 full battery symbol
elif percent > 20:
    icon = "\uf243" # 1/4 full battery symbol
else:
    icon = "\uf244" # Empty battery symbol

output = "{} {}%".format(icon, percent)

if percent < 10:
    output = error(output)
elif percent < 20:
    output = warning(output)

print(output)
