#!/usr/bin/env python3

import datetime

fontawesome = {
    'clock': '\uf017', # 
}

now = datetime.datetime.now()

timestamp = now.strftime('%a, %b %-e, %-l:%M %p').upper()

print(fontawesome['clock'] + ' ' + timestamp)
