#!/usr/bin/env bash

output=$(amixer get Master)

if [[ "$output" == *"[off]"* ]]; then
   echo " MUTED"
   exit 0
fi

percentage=$(echo $output | sed -E 's/.*\[([0-9]+)%\].*/\1/g')

if [ "${percentage}" -eq 0 ]; then
    icon=""
elif [ "${percentage}" -le 50 ]; then
    icon=""
else
    icon=""
fi

echo "${icon} ${percentage}%"
