#!/usr/bin/env python3

import subprocess
import colors
import re

fontawesome = {
    'volume-high':  '\uf028', # 
    'volume-low':   '\uf027', # 
    'volume-off':   '\uf026', # 
    'volume-xmark': '\uf6a9', # 
}

amixer_get_master = subprocess.run(['amixer', 'get', 'Master'], universal_newlines=True, check=False, capture_output=True)

if amixer_get_master.returncode != 0:
    print(colors.error(fontawesome['volume-xmark'] + ' UNKNOWN'))

    exit(0)

output = amixer_get_master.stdout

if '[off]' in output:
    print(colors.warning(fontawesome['volume-off'] + ' MUTED'))

    exit(0)

percentages = re.findall(r'\[(\d+)%\]', output)

percentages = list(map(int, percentages))

average_percentage = sum(percentages) // len(percentages)

if average_percentage == 0:
    icon = 'volume-off'
elif average_percentage < 50:
    icon = 'volume-low'
else:
    icon = 'volume-high'

print('{} {}%'.format(fontawesome[icon], average_percentage))
