#!/usr/bin/env bash

output=$(amixer get Master 2> /dev/null)

if [ "$?" -ne 0 ]; then
    echo "%{F#BF616A} UNKNOWN%{F-}"
    exit 0
fi

if [[ "$output" == *"[off]"* ]]; then
    echo "%{F#EBCB8B} MUTED%{F-}"
    exit 0
fi

percentage=$(echo $output | sed -E 's/.*\[([0-9]+)%\].*/\1/g')

if [ "${percentage}" -eq 0 ]; then
    icon=""
elif [ "${percentage}" -le 50 ]; then
    icon=""
else
    icon=""
fi

echo "${icon} ${percentage}%"
