#!/usr/bin/env python3

import subprocess
import re
import vm_detect
import colors
import truncate

vm_detect.exit_if_vm()

fontawesome = {
    'wifi': '\uf1eb', # 
}

nmcli_active_connection = subprocess.run(['nmcli', '-t', '-f', 'name,device', 'connection', 'show', '--active'], universal_newlines=True, check=False, capture_output=True)

wireless_connections = re.findall(r'(.*):wlp1s0', nmcli_active_connection.stdout)

if not wireless_connections:
    print(colors.error(fontawesome['wifi'] + ' NOT CONNECTED'))

    exit(0)

ssid = wireless_connections[0]

ssid = truncate.truncate(ssid, 40)

print(fontawesome['wifi'] + ' ' + ssid.upper())
