#!/usr/bin/env bash

# Hide when within a VM
if [ "$(systemd-detect-virt)" != "none" ]; then
    exit 0
fi

ssid="$(nmcli -t -f name,device connection show --active | grep wlp1s0 | cut -d: -f 1)"

if [ ${#ssid} -eq 0 ]; then
    echo "%{F#BF616A} NOT CONNECTED%{F-}"
    exit 33
fi

# Truncate long SSIDs
if [ ${#ssid} -ge 40 ]; then
    ssid="${ssid:0:40}..."
fi

# Uppercase
ssid="${ssid^^}"

echo " ${ssid}"
