#!/usr/bin/env bash

# Hide when within a VM
if [ "$(systemd-detect-virt)" != "none" ]; then
    exit 0
fi

ssid="$(nmcli connection show --active | grep wifi | awk '{print $1}')"

if [ $? -eq 255 ]; then
    echo "%{F#BF616A}NOT CONNECTED%{F-}"
    exit 33
fi

# Truncate long SSIDs
if [ ${#ssid} -ge 40 ]; then
    ssid="${ssid:0:40}..."
fi

# Uppercase
ssid="${ssid^^}"

echo " ${ssid}"
